# Generated by Django 3.0.8 on 2020-07-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200731_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
