# Generated by Django 3.0.8 on 2020-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_note_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
