# Generated by Django 3.0.8 on 2020-07-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200731_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users',
        ),
    ]
