# Generated by Django 3.0.8 on 2020-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_note_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
