# Generated by Django 3.0.8 on 2020-07-31 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200731_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users',
        ),
    ]
