# Generated by Django 3.0.8 on 2020-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_note_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
